-- Convert the TAGS (generated by `coqtags $(fd -e v)`) to ctags.
-- port of https://github.com/jalvesaq/Nvim-R/blob/master/R/nvimcom/R/etags2ctags.R
local etags2ctags = function (etags_file, ctags_file)
  local etags_lines = {}
  for line in io.lines(etags_file) do
    table.insert(etags_lines, line)
  end
  local etags_num_lines = #etags_lines
  local ctags_lines = {}
  local cur = 1
  while cur < etags_num_lines do
    if etags_lines[cur] == "\x0c" then
      cur = cur + 1
      local src_file, _ = etags_lines[cur]:gsub(",.*", "")
      cur = cur + 1
      local src_lines = {}
      for line in io.lines(src_file) do
        table.insert(src_lines, line)
      end
      while etags_lines[cur] ~= "\x0c" and cur <= etags_num_lines do
        local matchlist = vim.fn.matchlist(etags_lines[cur], "\\v^(.*)\x7f(.*)\x01(\\d*),(\\d*)$")
        local tag = matchlist[2+1]
        local src_lnum = tonumber(matchlist[3+1])
        local src = src_lines[src_lnum]
        local tag_line = vim.fn.printf("%s\t%s\t/^%s$/;\"\n", tag, src_file, src)
        table.insert(ctags_lines, tag_line)
        cur = cur + 1
      end
    else
      print('error at line', cur)
      return
    end
  end

  table.sort(ctags_lines)
  local file = io.open(ctags_file, "w")
  for _, line in ipairs(ctags_lines) do
    file:write(line)
  end
  file:close()
end

local run = function()
  local cwd = vim.loop.cwd()
  etags2ctags(cwd..'/TAGS', cwd..'/tags')
end

return run
